// import Header from "@/components/Header";
// import Footer from "@/components/Footer";
import "../src/scss/global.scss";

export const metadata = {
  title: "My Headless WordPress Site",
  description: "Next.js + WordPress Headless CMS",
};

const wordpressUrl = process.env.NEXT_PUBLIC_WORDPRESS_API_URL?.replace(/\/+$/, "");

async function getGlobalStyles() {
  if (!wordpressUrl) return "";

  try {
    const response = await fetch(
      `${wordpressUrl}/wp-json/headless/v1/global-styles`,
      { next: { revalidate: 60 } },
    );

    if (!response.ok) return "";

    const data = await response.json();
    return data.css ?? "";
  } catch {
    return "";
  }
}

export default async function RootLayout({ children }) {
  const globalStyles = await getGlobalStyles();

  return (
    <html lang="en">
      <head>
        {/* Gutenberg core styles */}
        <link
          rel="stylesheet"
          href={`${wordpressUrl}/wp-includes/css/dist/block-library/style.min.css`}
        />

        {/* Styles generated by the active WordPress theme.json */}
        <style
          id="wordpress-global-styles"
          dangerouslySetInnerHTML={{ __html: globalStyles }}
        />
      </head>
      <body>
        {/* Site Header */}
        {/* <Header /> */}

        {/* Page Content */}
        <main>{children}</main>

        {/* Site Footer */}
        {/* <Footer /> */}
      </body>
    </html>
  );
}
